version: '2'

volumes:

  mysql-data:
    driver: local

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=phpcomrapadura
      - MYSQL_USER=cababom
      - MYSQL_PASSWORD=secret

  app:
    image: ambientum/php:7.2-nginx
    container_name: app
    volumes:
      - ./application:/var/www/app
    ports:
      - "8000:8080"
    links:
      - mysql